import PricePlanner from "./price-planner";
import ReviewsSection from "./reviews-section";
import ServiceScope from "./service-scope";
import Concierge from "./concierge";
import "./premium-experience.css";

export const metadata = { title: "Charleston House Cleaning & Vacation Rental Care | Charleston Clean Routine", description: "Premium residential cleaning, vacation-rental and Airbnb care, and coordinated property services across Charleston and the Lowcountry. Clear pricing for homes and tailored plans for managed properties." };
function BrandLogo({ reversed = false }: { reversed?: boolean }) { return <a className="px-brand" href="#top" aria-label="Charleston Clean Routine home"><img src={reversed ? "/charleston-clean-routine-logo-reversed.svg" : "/charleston-clean-routine-logo.svg"} alt="Charleston Clean Routine" /></a>; }
export default function Home() { return <main id="top" className="px-home"><a className="skip-link" href="#main-content">Skip to content</a><header className="px-header"><BrandLogo /><nav aria-label="Primary navigation"><a href="#services">Services</a><a href="#scope">What’s Included</a><a href="/service-area">Service Area</a><a href="/contact">Contact</a></nav><a className="px-button px-button-small" href="#pricing-tool">Build My Routine</a></header>
<section className="px-hero" id="main-content"><div className="px-hero-copy"><p className="px-eyebrow">Residential cleaning + property care · Charleston & the Lowcountry</p><h1>Your home,<br /><span>handled.</span></h1><p className="px-lede">Thoughtful residential cleaning, vacation-rental and Airbnb care, and coordinated Portfolio Care—with clear expectations, meticulous standards, and less for you to manage.</p><div className="px-actions"><a className="px-button" href="#pricing-tool">Build My Routine</a><a className="px-button px-button-outline" href="/portfolio">Request a Property Plan</a></div><div className="px-proof"><span>Clear residential pricing</span><span>Carefully selected professionals</span><span>Defined service standards</span></div></div><figure className="px-hero-image"><img src="/%20%20%20%20ccr-tradd-street-hero.png" alt="A cared-for Charleston home on Tradd Street" /><figcaption><strong>The Charleston Finish</strong><span>Meticulous care. Quietly handled.</span></figcaption></figure></section>
<section className="px-services" id="services"><div className="px-section-head"><p className="px-eyebrow">Choose your path</p><h2>One standard of care.<br />Two simple ways to begin.</h2><p>Homes can build a routine and see residential pricing. Vacation rentals, Airbnb properties, and portfolios receive a reviewed property plan built around the way each property operates.</p></div><div className="px-path-grid"><article className="px-path px-path-primary"><div><span className="px-label">For residents</span><h3>Home Cleaning</h3><p>Routine, Deep, and Move-In / Move-Out cleaning for homes, apartments, condominiums, townhomes, and second homes.</p><div className="px-tags"><span>Routine</span><span>Deep</span><span>Move-In / Out</span><span>Recurring</span></div></div><a className="px-button" href="#pricing-tool">Build My Routine</a></article><article className="px-path"><div><span className="px-label">For hosts, owners + managers</span><h3>Property Care</h3><p>Vacation-rental turnovers, Airbnb care, guest-ready presentation, and coordinated multi-property service with property-specific requirements.</p><div className="px-tags"><span>Vacation Rental</span><span>Airbnb</span><span>Portfolio Care</span><span>Turnovers</span></div></div><a className="px-button px-button-outline" href="/portfolio">Request a Property Plan</a></article></div></section>
<div id="scope"><ServiceScope /></div><PricePlanner />
<section className="px-standard"><div className="px-section-head"><p className="px-eyebrow">A higher standard from day one</p><h2>Trust is built in the details.</h2><p>We designed Charleston Clean Routine around the things clients should not have to chase: clarity, reliability, accountability, and consistent care.</p></div><div className="px-standard-grid"><article><span>01</span><h3>Know what you’re choosing.</h3><p>Clear scope, service levels, options, and residential pricing before you commit.</p></article><article><span>02</span><h3>Know what to expect.</h3><p>Defined standards and property instructions create consistency from visit to visit.</p></article><article><span>03</span><h3>Know we’ll address it.</h3><p>If something is not right, we communicate clearly and work to make it right.</p></article><article><span>04</span><h3>People treated well do better work.</h3><p>We respect our cleaning professionals, compensate them fairly, and set them up to succeed.</p></article></div></section><ReviewsSection />
<section className="px-final"><p className="px-eyebrow">Charleston Clean Routine</p><h2>Ready to have one less thing to manage?</h2><p>Build your residential routine and see your price, or tell us about a vacation rental, Airbnb, or property portfolio and we’ll prepare the right plan.</p><div className="px-actions"><a className="px-button px-button-light" href="#pricing-tool">Build My Routine</a><a className="px-button px-button-ghost-light" href="/portfolio">Request a Property Plan</a></div></section><footer className="px-footer"><BrandLogo reversed /><div><a href="/service-area">Service Area</a><a href="/contact">Contact</a><a href="/login">Client Portal</a><a href="/provider-application">Join Our Team</a></div><p>Charleston & surrounding Lowcountry communities · Your home, handled.</p></footer><Concierge /></main>; }
